- .env
- K8s/helm/Chart.yaml
- K8s/helm/templates/cart-deployment.yaml
- K8s/helm/templates/catalogue-deployment.yaml
- K8s/helm/templates/dispatch-deployment.yaml
- K8s/helm/templates/mongodb-deployment.yaml
- K8s/helm/templates/mysql-deployment.yaml
- K8s/helm/templates/payment-deployment.yaml
- K8s/helm/templates/ratings-deployment.yaml
- K8s/helm/templates/shipping-deployment.yaml
- K8s/helm/templates/user-deployment.yaml
- K8s/helm/templates/web-deployment.yaml
- K8s/helm/values.yaml
- cart/package.json
- catalogue/package.json
- docker-compose.yaml
- user/package.json
> Asserts Docker Repo and NodeJS Service instrumentation

- K8s/helm/templates/redis-statefulset.yaml
> Setup redis exporter. The prometheus scrape configuration is still a TBD

- K8s/helm/templates/payment-service-monitor.yaml
- K8s/helm/templates/redis-statefulset.yaml
- K8s/mysql/mysql-values.yaml
- K8s/redis/redis-values.yaml
- payment/payment.py
- payment/requirements.txt
[sc-12566]
- added helm chart values file for mysql & redis
- configure flask prometheus exporter for payment python service
> setup monitoring for mysql, redis and payment services

- .env
> Set version tag

- K8s/mongodb/mongodb-exporter-values.yaml
> Add Percona Mongo DB Exporter

- K8s/mongodb/mongodb-exporter-values.yaml
> Make mongodb chart values yaml concise

- K8s/rabbitmq/rabbitmq-values.yaml
> setup rabbitmq monitoring

- K8s/helm/templates/mongodb-service.yaml
- K8s/install-all.sh
- K8s/mongodb/mongodb-exporter-servicemonitor.yaml
- K8s/mongodb/mongodb-exporter-values.yaml
> Service Monitor for mongo db exporter

- K8s/helm/templates/web-service.yaml
- K8s/helm/values.yaml
- K8s/ingress/ingress.yaml
- K8s/ingress/values.yaml
- K8s/install-all.sh
> Add nginx ingress to route requests to backend services

- cart/server.js
- user/server.js
> Mask ids in URLs

- payment/payment.py
> Fix cardinality of payment service metrics

- K8s/helm/templates/rabbitmq-deployment.yaml
- K8s/helm/templates/rabbitmq-service-monitor.yaml
- K8s/helm/templates/rabbitmq-service.yaml
- K8s/install-all.sh
> Upgrade rabbitmq to 3.10.6 and enable prometheus plugin

- K8s/mongodb/mongodb-exporter-values.yaml
> Enable compatibility mode

- K8s/helm/templates/dispatch-service-monitor.yaml
- K8s/helm/templates/dispatch-service.yaml
- dispatch/Dockerfile
- dispatch/main.go
> Add prometheus monitoring for dispatch go service

- payment/payment.py
> Log exception stacktrace in payment module

- .env
- K8s/load-deployment.yaml
- load-gen/build.sh
- load-gen/robot-shop.py
[sc-12566]
- The load-gen generates a lot of unique URLs and the statistics are captured
for each of these. Grouping them will result in a stable list of URLs for
which statistics are captured instead of an ever-growing list of URLs.
https://docs.locust.io/en/latest/writing-a-locustfile.html#grouping-requests
> Fix excessive cpu & memory utilization by load-gen

- load-gen/robot-shop.py
- payment/payment.py
- shipping/src/main/java/com/instana/robotshop/shipping/Controller.java
> Trigger problems in shipping and payment services at regular intervals

- cart/server.js
- payment/payment.py
- payment/requirements.txt
> Payment service amend triggers errors in both payment and cart services

- cart/server.js
- catalogue/server.js
- user/server.js
> Reduce logs verbosity

- .gitignore
- K8s/helm/templates/shipping-deployment.yaml
- K8s/load-deployment.yaml
> Bump cpu and memory for load and shipping services

- config/custom-thresholds.yml
- config/disabled-alerts.yml
- config/robot-shop-p99.yml
- config/robot_shop_services_calls_record.yml
- config/user-defined-relations.yml
> Asserts config files

- load-gen/robot-shop.py
> Reduce failures frequency

- K8s/helm/values.yaml
- config/robot-shop-p99.yml
- payment/payment.py
> Config to make payment gateway call optional

- K8s/helm/templates/rabbitmq-deployment.yaml
- K8s/helm/values.yaml
- K8s/install-demo.sh
Update robot-shop app with rabbitmq exporter flag. Also add script to install in demo cluster with comments of supporting services/ingress locations.
> Add demo install and exporter flag

- docker-compose.yaml
- jaeger-sampling.json
- shipping/Dockerfile
Jaeger tracing for shipping app.
Default sampling configuration added, but need to relook as it is not getting applied properly.
[ch13936]
> Add jaeger tracing for robot-shop app

- K8s/helm/templates/jaeger-deployment.yaml
- K8s/helm/templates/jaeger-service.yaml
- K8s/ingress/ingress.yaml
- K8s/ingress/jaeger-ingress.yaml
Adding deployment and service config for jaeger
adding ingress for Jaeger service
[ch13936]
> Add k8s deployment changes for jaeger

- K8s/helm/templates/jaeger-deployment.yaml
increase the memory for jaeger any query in UI crashes the jaeger service it is going OOM.
[ch13936]
> Increase memory for jaeger

- K8s/helm/templates/elasticsearch-statefulset.yaml
Adding the permission in initContainers section.
[ch14462]
> add initContainers section for elastic

- K8s/helm/templates/elasticsearch-statefulset.yaml
- K8s/helm/templates/esindex-cleaner-cron.yaml
- K8s/install-demo.sh
Increase trace retention days to the last 7 days.
> Increase elastic search storage for last 7 days
